#!/bin/sh /etc/rc.common


# directory and file to backup to
BACKUP_DIR=/etc/collectd
BACKUP_FILE=rrdbackup.tgz

# the directory containing RRD files (usually /tmp/rrd)
# needs to be relative to root, i.e. no slash in front (to mitigate tar "leading '/'" warning)
RRD_DIR=tmp/rrd


# queue rrdbackup to start before collectd starts (80) and stop after collect stops (10):
START=79
STOP=11

# command to manually backup database (e.g. from cronjob)
EXTRA_COMMANDS="backup restore"
EXTRA_HELP="        backup          Backup current rrd database"

backup() {
	local TMP_FILE=$(mktemp -u)
	tar -czf $TMP_FILE -C / $RRD_DIR
	mkdir -p $BACKUP_DIR
	mv $TMP_FILE "$BACKUP_DIR/$BACKUP_FILE"
	rm -f $TMP_FILE
}

restore() {
	[[ -f "$BACKUP_DIR/$BACKUP_FILE" ]] && tar -xzf "$BACKUP_DIR/$BACKUP_FILE" -C /
}

start() {
	restore
}

stop() {
	backup
}

